# Adapted from https://github.com/pichenettes/mutable-dev-environment
# and https://www.openstm32.org/System+Workbench+for+STM32
# See LICENSE.md for details

# Packages to build
TARGET         = osc3
TARGET_ID		= 06
TARGET_VERSION	= 01

include hardware_drivers/makefile.inc