# Adapted from https://github.com/pichenettes/mutable-dev-environment
# and https://www.openstm32.org/System+Workbench+for+STM32
# See LICENSE.md for details

# Packages to build
TARGET         = meta

include hardware_drivers/makefile.inc