# Adapted from https://github.com/pichenettes/mutable-dev-environment
# and https://www.openstm32.org/System+Workbench+for+STM32
# See LICENSE.md for details

# folder name, token, general identifyier
TARGET         = emptyvia
# enum for flasher recognition/calibration storage, as hex 0-255
TARGET_ID		= 00
# version number, as hex 0-255
TARGET_VERSION	= 00

include hardware_drivers/makefile.inc